version: '3'

services: 
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports: 
      - "8000:8000"
    volumes: 
      - .:/app
    networks: 
      - django_mysql
    depends_on: 
      - db
  db:
    image: mysql:5.7
    # command: --default-authentication-plugin=mysql_native_password
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    networks: 
      - django_mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=database
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    ports:
      - 6033:3306
networks: 
  django_mysql:
volumes: 
  mysql_data:
